title: Falix Help Center
logo: "/assets/images/Icon.png"
baseurl: ""
url: ""
theme: minima

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-avatar

whitelist:
  - jekyll-redirect-from

algolia:
  application_id: '${{ secrets.ALGOLIA_ID }}'
  index_name: ${{ secrets.ALGOLIA_INDEX_NAME }}
  search_only_api_key: '${{ secrets.ALGOLIA_SEARCH_ONLY_API_KEY }}'

stickyposts:
  debug: true
  reverse: false
  retain: true
  reverse_sticky: false 