title: Falix Help Center
logo: "/assets/images/Icon.png"
baseurl: ""
url: ""
theme: minima

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-avatar

whitelist:
  - jekyll-redirect-from

stickyposts:
#enabled: false   # Enable StickyPosts; default: true
debug: true       # Show additional info; default: false
sort: "blah"      # Optional sort field; default: "date", use "none" to avoid sorting
reverse: false     # Ascending order, default: false
retain: true      # Also show sticky posts in their original positions; default: false
reverse_sticky: false    # Reverse the order of the sticky posts, e.g. oldest first; default: false 