title: Falix Help Center
logo: "/assets/images/Icon.png"
baseurl: ""
url: ""
theme: minima

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-avatar

whitelist:
  - jekyll-redirect-from

algolia:
  application_id: '${{ secrets.ALGOLIA_ID }}'
  index_name: ${{ secrets.ALGOLIA_INDEX_NAME }}
  search_only_api_key: '${{ secrets.ALGOLIA_SEARCH_ONLY_API_KEY }}'

stickyposts:
#enabled: false   # Enable StickyPosts; default: true
debug: true       # Show additional info; default: false
sort: "blah"      # Optional sort field; default: "date", use "none" to avoid sorting
reverse: false     # Ascending order, default: false
retain: true      # Also show sticky posts in their original positions; default: false
reverse_sticky: false    # Reverse the order of the sticky posts, e.g. oldest first; default: false 