name: Rebuild and Update Website on VPS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Copy configuration
      run: sudo cp /usr/share/korbs-studio/help-center/_config.yml ./
    - name: Update Algolia Search
      run: sudo ALGOLIA_API_KEY='${{ secrets.ALGOLIA_API_KEY}}' bundle exec jekyll algolia
    - name: Build the site in the jekyll/builder container
      run: JEKYLL_ENV=production bundle exec jekyll build